### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by oroojlooy** [MykolaHerasymovych/Optimizing-Acceptance-Threshold-in-Credit-Scoring-using-Reinforcement-Learning#2]
I was wondering how can I run the code? 
The shared code includes all the implemented classes with the required functions, but the main file which instantiates the class and run the functions of the class is not shared. I tried to write that function which creates an instance of the `Manager` class and calls `initExperiment` and `train` functions, but it fails to start the training. In the `__init__` of the environment, `self.model.partial_fit(env.action_space.sample(), [0])`, I get 

```
/home/.local/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Traceback (most recent call last):
  File "/home/pycharm-2020.2/plugins/python/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/pycharm-2020.2/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/credit_assignment/source/manager.py", line 768, in <module>
    model = Manager(None)
  File "/home/credit_assignment/source/manager.py", line 26, in __init__
    self.agent = self.initAgent() if agent is None else agent
  File "/home/credit_assignment/source/manager.py", line 38, in initAgent
    env_model = EnvironmentModel(env, lr)
  File "/home/credit_assignment/source/model.py", line 114, in __init__
    self.model.partial_fit(env.action_space.sample(), [0])
  File "/home/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1185, in partial_fit
    intercept_init=None)
  File "/home/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1131, in _partial_fit
    accept_large_sparse=False)
  File "/home/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 432, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py", line 802, in check_X_y
    estimator=estimator)
  File "/home/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py", line 616, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got scalar array instead:
array=10.0.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
python-BaseException
```

**Comment by SSwasm** [comment]
You may be can modify model.py Class EnvironmentModel, from env.action_space.sample() to np.array(env.action_space.sample()).reshape(1, -1)
